modules = ""

modules += "\n// CLIENT RECORDS MODULE\n"
modules += "export async function clientRecordsModule(fastify: any) {\n"
modules += "  fastify.get(" + '"/client-records/:clientId"' + ", { preHandler: [authenticate] }, async (req: any, reply: any) => {\n"
modules += "    const { tenantId } = req.tenantContext;\n"
modules += "    const data = await db.execute(sql" + "`" + "SELECT * FROM client_records WHERE tenant_id = ${tenantId} AND client_id = ${req.params.clientId} ORDER BY created_at DESC" + "`" + ");\n"
modules += "    return reply.send({ success: true, data: (data as any).rows ?? [] });\n"
modules += "  });\n"
modules += "  fastify.post(" + '"/client-records"' + ", { preHandler: [authenticate] }, async (req: any, reply: any) => {\n"
modules += "    const { tenantId, userId } = req.tenantContext;\n"
modules += "    const b = req.body as any;\n"
modules += "    const data = await db.execute(sql" + "`" + "INSERT INTO client_records (tenant_id,client_id,type,medications,medical_history,previous_procedures,skin_type,contraindications,notes,created_by) VALUES (${tenantId},${b.clientId},'anamnesis',${b.medications??null},${b.medicalHistory??null},${b.previousProcedures??null},${b.skinType??null},${b.contraindications??null},${b.notes??null},${userId}) RETURNING *" + "`" + ");\n"
modules += "    return reply.status(201).send({ success: true, data: ((data as any).rows??[])[0] });\n"
modules += "  });\n"
modules += "  fastify.patch(" + '"/client-records/:id"' + ", { preHandler: [authenticate] }, async (req: any, reply: any) => {\n"
modules += "    const { tenantId } = req.tenantContext;\n"
modules += "    const b = req.body as any;\n"
modules += "    const data = await db.execute(sql" + "`" + "UPDATE client_records SET medications=COALESCE(${b.medications??null},medications),medical_history=COALESCE(${b.medicalHistory??null},medical_history),notes=COALESCE(${b.notes??null},notes),updated_at=NOW() WHERE id=${req.params.id} AND tenant_id=${tenantId} RETURNING *" + "`" + ");\n"
modules += "    return reply.send({ success: true, data: ((data as any).rows??[])[0] });\n"
modules += "  });\n"
modules += "}\n"

modules += "\n// CONSENT FORMS MODULE\n"
modules += "export async function consentFormsModule(fastify: any) {\n"
modules += "  fastify.get(" + '"/consent-forms/:clientId"' + ", { preHandler: [authenticate] }, async (req: any, reply: any) => {\n"
modules += "    const { tenantId } = req.tenantContext;\n"
modules += "    const data = await db.execute(sql" + "`" + "SELECT * FROM consent_forms WHERE tenant_id = ${tenantId} AND client_id = ${req.params.clientId} ORDER BY created_at DESC" + "`" + ");\n"
modules += "    return reply.send({ success: true, data: (data as any).rows ?? [] });\n"
modules += "  });\n"
modules += "  fastify.post(" + '"/consent-forms"' + ", { preHandler: [authenticate] }, async (req: any, reply: any) => {\n"
modules += "    const { tenantId, userId } = req.tenantContext;\n"
modules += "    const b = req.body as any;\n"
modules += "    const data = await db.execute(sql" + "`" + "INSERT INTO consent_forms (tenant_id,client_id,type,content,created_by) VALUES (${tenantId},${b.clientId},${b.type??'lgpd'},${b.content??null},${userId}) RETURNING *" + "`" + ");\n"
modules += "    return reply.status(201).send({ success: true, data: ((data as any).rows??[])[0] });\n"
modules += "  });\n"
modules += "  fastify.delete(" + '"/consent-forms/:id"' + ", { preHandler: [authenticate] }, async (req: any, reply: any) => {\n"
modules += "    const { tenantId } = req.tenantContext;\n"
modules += "    await db.execute(sql" + "`" + "DELETE FROM consent_forms WHERE id=${req.params.id} AND tenant_id=${tenantId}" + "`" + ");\n"
modules += "    return reply.status(204).send();\n"
modules += "  });\n"
modules += "}\n"

modules += "\n// APPOINTMENT PHOTOS MODULE\n"
modules += "export async function appointmentPhotosModule(fastify: any) {\n"
modules += "  fastify.get(" + '"/appointment-photos/:clientId"' + ", { preHandler: [authenticate] }, async (req: any, reply: any) => {\n"
modules += "    const { tenantId } = req.tenantContext;\n"
modules += "    const data = await db.execute(sql" + "`" + "SELECT * FROM appointment_photos WHERE tenant_id = ${tenantId} AND client_id = ${req.params.clientId} ORDER BY taken_at DESC" + "`" + ");\n"
modules += "    return reply.send({ success: true, data: (data as any).rows ?? [] });\n"
modules += "  });\n"
modules += "  fastify.post(" + '"/appointment-photos"' + ", { preHandler: [authenticate] }, async (req: any, reply: any) => {\n"
modules += "    const { tenantId, userId } = req.tenantContext;\n"
modules += "    const b = req.body as any;\n"
modules += "    const data = await db.execute(sql" + "`" + "INSERT INTO appointment_photos (tenant_id,client_id,appointment_id,type,storage_path,public_url,description,created_by) VALUES (${tenantId},${b.clientId},${b.appointmentId??null},${b.type??'before'},${b.storagePath},${b.publicUrl??null},${b.description??null},${userId}) RETURNING *" + "`" + ");\n"
modules += "    return reply.status(201).send({ success: true, data: ((data as any).rows??[])[0] });\n"
modules += "  });\n"
modules += "  fastify.delete(" + '"/appointment-photos/:id"' + ", { preHandler: [authenticate] }, async (req: any, reply: any) => {\n"
modules += "    const { tenantId } = req.tenantContext;\n"
modules += "    await db.execute(sql" + "`" + "DELETE FROM appointment_photos WHERE id=${req.params.id} AND tenant_id=${tenantId}" + "`" + ");\n"
modules += "    return reply.status(204).send();\n"
modules += "  });\n"
modules += "}\n"

modules += "\n// PROTOCOLS MODULE\n"
modules += "export async function protocolsModule(fastify: any) {\n"
modules += "  fastify.get(" + '"/protocols"' + ", { preHandler: [authenticate] }, async (req: any, reply: any) => {\n"
modules += "    const { tenantId } = req.tenantContext;\n"
modules += "    const data = await db.execute(sql" + "`" + "SELECT * FROM protocols WHERE tenant_id = ${tenantId} AND is_active = true ORDER BY name" + "`" + ");\n"
modules += "    return reply.send({ success: true, data: (data as any).rows ?? [] });\n"
modules += "  });\n"
modules += "  fastify.post(" + '"/protocols"' + ", { preHandler: [authenticate] }, async (req: any, reply: any) => {\n"
modules += "    const { tenantId, userId } = req.tenantContext;\n"
modules += "    const b = req.body as any;\n"
modules += "    const data = await db.execute(sql" + "`" + "INSERT INTO protocols (tenant_id,name,description,service_id,created_by) VALUES (${tenantId},${b.name},${b.description??null},${b.serviceId??null},${userId}) RETURNING *" + "`" + ");\n"
modules += "    return reply.status(201).send({ success: true, data: ((data as any).rows??[])[0] });\n"
modules += "  });\n"
modules += "  fastify.patch(" + '"/protocols/:id"' + ", { preHandler: [authenticate] }, async (req: any, reply: any) => {\n"
modules += "    const { tenantId } = req.tenantContext;\n"
modules += "    const b = req.body as any;\n"
modules += "    const data = await db.execute(sql" + "`" + "UPDATE protocols SET name=COALESCE(${b.name??null},name),is_active=COALESCE(${b.isActive??null},is_active),updated_at=NOW() WHERE id=${req.params.id} AND tenant_id=${tenantId} RETURNING *" + "`" + ");\n"
modules += "    return reply.send({ success: true, data: ((data as any).rows??[])[0] });\n"
modules += "  });\n"
modules += "  fastify.delete(" + '"/protocols/:id"' + ", { preHandler: [authenticate] }, async (req: any, reply: any) => {\n"
modules += "    const { tenantId } = req.tenantContext;\n"
modules += "    await db.execute(sql" + "`" + "UPDATE protocols SET is_active=false,updated_at=NOW() WHERE id=${req.params.id} AND tenant_id=${tenantId}" + "`" + ");\n"
modules += "    return reply.status(204).send();\n"
modules += "  });\n"
modules += "}\n\n"

original = open("C:/projetos/beautytech-v2/backend/src/modules/all-modules_original.ts", encoding="utf-16").read()
old_export = "export { whatsappModule } from './whatsapp/whatsapp.routes.js';"
result = original.replace(old_export, modules + old_export, 1)
open("C:/projetos/beautytech-v2/backend/src/modules/all-modules.ts", "w", encoding="utf-8").write(result)
print("DONE - linhas:", len(result.split("\n")))
print("clientRecords:", "clientRecordsModule" in result)
print("demoModule:", "Demo Lead Maria" in result)
print("corrompido:", "sqlSELECT" in result)
